# Generated by Django 5.0.6 on 2026-04-17 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ferme', '0002_initial'),
        ('produits', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consommation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consommation', models.DateField()),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ferme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss_ferme', to='ferme.ferme')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consommations', to='ferme.lot')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='produits.produit')),
            ],
        ),
    ]
