# Generated by Django 5.0.6 on 2026-04-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_produit_organisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='ferme',
        ),
        migrations.AddField(
            model_name='produit',
            name='entite_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='entite_type',
            field=models.CharField(choices=[('ferme', 'Ferme'), ('boutique', 'Boutique')], default='ferme', max_length=20),
        ),
    ]
