# Generated by Django 5.0.6 on 2026-04-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0003_remove_produit_ferme_produit_entite_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='unite',
            field=models.CharField(default='unité', help_text='Unité de mesure (ex: kg, sac, boîte)', max_length=20),
        ),
    ]
