# Generated by Django 5.0.6 on 2026-04-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaires', '0002_remove_contrat_ferme_remove_intervention_ferme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='entite_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='entite_type',
            field=models.CharField(choices=[('ferme', 'Ferme'), ('boutique', 'Boutique')], default='ferme', max_length=20),
        ),
        migrations.AddField(
            model_name='intervention',
            name='entite_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='entite_type',
            field=models.CharField(choices=[('ferme', 'Ferme'), ('boutique', 'Boutique')], default='ferme', max_length=20),
        ),
        migrations.AddField(
            model_name='veterinaire',
            name='entite_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veterinaire',
            name='entite_type',
            field=models.CharField(choices=[('ferme', 'Ferme'), ('boutique', 'Boutique')], default='ferme', max_length=20),
        ),
    ]
