# Generated by Django 5.0.6 on 2026-04-17 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ferme', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CofoOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(choices=[('achat', 'Achat'), ('vente', 'Vente')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fournisseur', models.CharField(blank=True, max_length=150, null=True)),
                ('client', models.CharField(blank=True, max_length=150, null=True)),
                ('quantite_sacs', models.IntegerField(blank=True, null=True)),
                ('date_operation', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ferme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss_ferme', to='ferme.ferme')),
            ],
        ),
    ]
