# Generated by Django 5.0.6 on 2026-04-17 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='ferme',
        ),
        migrations.AddField(
            model_name='vente',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='organisations.organisation'),
        ),
    ]
