# Generated by Django 5.0.6 on 2026-04-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0002_remove_vente_ferme_vente_organisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignevente',
            name='ferme',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='id_boutique',
        ),
        migrations.AddField(
            model_name='vente',
            name='entite_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='entite_type',
            field=models.CharField(choices=[('ferme', 'Ferme'), ('boutique', 'Boutique')], default='ferme', max_length=20),
        ),
    ]
