# Generated by Django 5.0.6 on 2026-04-21 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_remove_portefeuille_id_entite_and_more'),
        ('ventes', '0003_remove_lignevente_ferme_remove_vente_id_boutique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='portefeuille',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='finances.portefeuille'),
        ),
    ]
