# Generated by Django 5.0.6 on 2026-04-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0004_vente_portefeuille'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='date_livraison',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé (Livré)'), ('annule', 'Annulé')], default='brouillon', max_length=20),
        ),
    ]
