# Generated by Django 5.0.6 on 2026-04-23 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiques', '0002_boutique_organisation_boutique_responsable_and_more'),
        ('ventes', '0005_vente_date_livraison_vente_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='boutique_dest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_recues', to='boutiques.boutique'),
        ),
    ]
