# Generated by Django 5.0.6 on 2026-04-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0006_vente_boutique_dest'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='date_reception',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='reception_confirmee',
            field=models.BooleanField(default=False),
        ),
    ]
