# Generated by Django 5.0.6 on 2026-04-17 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs', to='organisations.organisation'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('pdg', 'PDG'), ('controleur', 'Contrôleur'), ('gerant', 'Gérant de Boutique'), ('vendeur', 'Vendeur')], default='controleur', max_length=20),
        ),
    ]
