# Generated by Django 5.0.6 on 2026-04-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_utilisateur_entite_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='doit_changer_mdp',
            field=models.BooleanField(default=False),
        ),
    ]
