# Generated by Django 5.0.6 on 2026-04-17 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0001_initial'),
        ('boutiques', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='id_boutique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='boutiques.boutique'),
        ),
    ]
