# Generated by Django 5.0.6 on 2026-04-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0003_remove_achat_ferme_achat_organisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achat',
            name='id_boutique',
        ),
        migrations.RemoveField(
            model_name='ligneachat',
            name='ferme',
        ),
        migrations.AddField(
            model_name='achat',
            name='entite_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='achat',
            name='entite_type',
            field=models.CharField(choices=[('ferme', 'Ferme'), ('boutique', 'Boutique')], default='ferme', max_length=20),
        ),
    ]
