# Generated by Django 5.0.6 on 2026-04-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0005_achat_portefeuille'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='date_reception',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='achat',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé (Réceptionné)'), ('annule', 'Annulé')], default='brouillon', max_length=20),
        ),
    ]
