# Generated by Django 5.0.6 on 2026-04-23 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0006_achat_date_reception_achat_statut'),
        ('partenaires', '0004_remove_partenaire_id_boutique'),
        ('ventes', '0007_vente_date_reception_vente_reception_confirmee'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='vente_fournisseuse',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achat_miroir', to='ventes.vente'),
        ),
        migrations.AlterField(
            model_name='achat',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='achats', to='partenaires.partenaire'),
        ),
    ]
