# Generated by Django 5.0.6 on 2026-04-17 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('charges', '__first__'),
        ('ferme', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portefeuille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('caisse', 'Caisse'), ('banque', 'Banque')], max_length=20)),
                ('id_entite', models.IntegerField()),
                ('type_entite', models.CharField(choices=[('ferme', 'Ferme'), ('boutique', 'Boutique')], max_length=20)),
                ('solde_init', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('solde_actuel', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nom_banque', models.CharField(blank=True, max_length=150, null=True)),
                ('numero_compte', models.CharField(blank=True, max_length=80, null=True)),
                ('titulaire', models.CharField(blank=True, max_length=150, null=True)),
                ('devise', models.CharField(default='GNF', max_length=10)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('cloture', 'Clôturé')], default='actif', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ferme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss_ferme', to='ferme.ferme')),
            ],
        ),
        migrations.CreateModel(
            name='MouvementCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('portefeuille', 'Portefeuille'), ('tiers', 'Tiers')], max_length=20)),
                ('dest_type', models.CharField(choices=[('portefeuille', 'Portefeuille'), ('tiers', 'Tiers')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nature', models.CharField(choices=[('vente', 'Vente'), ('achat', 'Achat'), ('achat_cofo', 'Achat COFO'), ('vente_cofo', 'Vente COFO'), ('veterinaire', 'Vétérinaire'), ('charge', 'Charge'), ('transfert_portefeuille', 'Transfert Portefeuille')], max_length=50)),
                ('reference_table', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_mouvement', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ferme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss_ferme', to='ferme.ferme')),
                ('id_type_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='charges.typecharge')),
                ('dest_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='mouvements_entrants', to='finances.portefeuille')),
                ('source_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='mouvements_sortants', to='finances.portefeuille')),
            ],
        ),
    ]
