# Generated by Django 5.0.6 on 2026-04-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_remove_mouvementcaisse_ferme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portefeuille',
            name='id_entite',
        ),
        migrations.RemoveField(
            model_name='portefeuille',
            name='type_entite',
        ),
        migrations.AddField(
            model_name='portefeuille',
            name='entite_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portefeuille',
            name='entite_type',
            field=models.CharField(blank=True, choices=[('ferme', 'Ferme'), ('boutique', 'Boutique')], max_length=20, null=True),
        ),
    ]
