# Generated by Django 5.0.6 on 2026-04-23 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0007_achat_vente_fournisseuse_alter_achat_fournisseur'),
        ('finances', '0003_remove_portefeuille_id_entite_and_more'),
        ('organisations', '0002_organisation_id_proprietaire'),
        ('ventes', '0007_vente_date_reception_vente_reception_confirmee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandePaiementInterne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('achat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_paiement', to='achats.achat')),
                ('dest_portefeuille', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='demandes_paiement_entrantes', to='finances.portefeuille')),
                ('initiateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_initiees', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_paiement', to='organisations.organisation')),
                ('source_portefeuille', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='demandes_paiement_sortantes', to='finances.portefeuille')),
                ('validateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_validees', to=settings.AUTH_USER_MODEL)),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_paiement', to='ventes.vente')),
            ],
        ),
    ]
