# Generated by Django 5.0.6 on 2026-04-17 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mouvementstock',
            name='ferme',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='ferme',
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_stock', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='stock',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='organisations.organisation'),
        ),
    ]
