# Generated by Django 5.0.6 on 2026-04-21 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0003_remove_produit_ferme_produit_entite_id_and_more'),
        ('stocks', '0003_mouvementstock_entite_id_mouvementstock_entite_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='produits.produit'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('produit', 'entite_type', 'entite_id')},
        ),
    ]
