# Generated by Django 5.0.6 on 2026-04-17 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiques', '0001_initial'),
        ('partenaires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaire',
            name='id_boutique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partenaires', to='boutiques.boutique'),
        ),
    ]
