# Generated by Django 5.0.6 on 2026-04-17 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
        ('partenaires', '0002_partenaire_id_boutique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partenaire',
            name='ferme',
        ),
        migrations.AddField(
            model_name='partenaire',
            name='entite_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='entite_type',
            field=models.CharField(choices=[('ferme', 'Ferme'), ('boutique', 'Boutique')], default='ferme', max_length=20),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partenaires', to='organisations.organisation'),
        ),
    ]
