# Generated by Django 5.0.6 on 2026-04-17 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partenaires', '0003_remove_partenaire_ferme_partenaire_entite_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partenaire',
            name='id_boutique',
        ),
    ]
