# Generated by Django 5.0.6 on 2026-04-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0002_remove_mortalite_ferme_remove_traitement_ferme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortalite',
            name='entite_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mortalite',
            name='entite_type',
            field=models.CharField(choices=[('ferme', 'Ferme'), ('boutique', 'Boutique')], default='ferme', max_length=20),
        ),
        migrations.AddField(
            model_name='traitement',
            name='entite_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traitement',
            name='entite_type',
            field=models.CharField(choices=[('ferme', 'Ferme'), ('boutique', 'Boutique')], default='ferme', max_length=20),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='entite_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='entite_type',
            field=models.CharField(choices=[('ferme', 'Ferme'), ('boutique', 'Boutique')], default='ferme', max_length=20),
        ),
    ]
