# Generated by Django 5.0.6 on 2026-04-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0003_mortalite_entite_id_mortalite_entite_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traitement',
            name='quantite',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='quantite',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
