# Generated by Django 5.0.6 on 2026-04-24 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0004_traitement_quantite_vaccination_quantite'),
        ('veterinaires', '0003_contrat_entite_id_contrat_entite_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traitement',
            name='veterinaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traitements', to='veterinaires.veterinaire'),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='veterinaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccinations', to='veterinaires.veterinaire'),
        ),
    ]
