# Generated by Django 5.0.6 on 2026-04-17 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ferme', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportjournalier',
            name='redacteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_rediges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rapportjournalier',
            name='validateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionoeuf',
            name='rapport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='ferme.rapportjournalier'),
        ),
    ]
