# Generated by Django 5.0.6 on 2026-04-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferme', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferme',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ferme',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ferme',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ferme',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='fermes/logos/'),
        ),
        migrations.AddField(
            model_name='ferme',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ferme',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
