# Generated by Django 5.0.6 on 2026-04-17 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferme', '0003_ferme_actif_ferme_adresse_ferme_email_ferme_logo_and_more'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferme',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ferme',
            name='organisation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ferme', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='ferme',
            name='superficie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
