# Generated by Django 5.0.6 on 2026-04-17 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferme', '0004_ferme_notes_ferme_organisation_ferme_superficie'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='productionoeuf',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productions_oeufs', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='rapportjournalier',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rapports_journaliers', to='organisations.organisation'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='ferme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='ferme.ferme'),
        ),
        migrations.AlterField(
            model_name='productionoeuf',
            name='ferme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productions_oeufs', to='ferme.ferme'),
        ),
        migrations.AlterField(
            model_name='productionoeuf',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss_lot', to='ferme.lot'),
        ),
        migrations.AlterField(
            model_name='rapportjournalier',
            name='ferme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rapports_journaliers', to='ferme.ferme'),
        ),
    ]
