# Generated by Django 5.0.6 on 2026-04-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferme', '0005_lot_organisation_productionoeuf_organisation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='ferme',
        ),
        migrations.RemoveField(
            model_name='productionoeuf',
            name='ferme',
        ),
        migrations.RemoveField(
            model_name='rapportjournalier',
            name='ferme',
        ),
        migrations.AddField(
            model_name='lot',
            name='entite_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='entite_type',
            field=models.CharField(choices=[('ferme', 'Ferme'), ('boutique', 'Boutique')], default='ferme', max_length=20),
        ),
        migrations.AddField(
            model_name='productionoeuf',
            name='entite_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionoeuf',
            name='entite_type',
            field=models.CharField(choices=[('ferme', 'Ferme'), ('boutique', 'Boutique')], default='ferme', max_length=20),
        ),
        migrations.AddField(
            model_name='rapportjournalier',
            name='entite_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rapportjournalier',
            name='entite_type',
            field=models.CharField(choices=[('ferme', 'Ferme'), ('boutique', 'Boutique')], default='ferme', max_length=20),
        ),
    ]
