# Generated by Django 5.0.6 on 2026-04-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferme', '0006_remove_lot_ferme_remove_productionoeuf_ferme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='quantite_actuelle',
            field=models.IntegerField(default=0),
        ),
    ]
