# Generated by Django 5.0.6 on 2026-04-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('pays', models.CharField(max_length=50)),
                ('devise', models.CharField(default='GNF', max_length=10)),
                ('email_contact', models.EmailField(max_length=150)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organisations/logos/')),
                ('plan', models.CharField(choices=[('gratuit', 'Gratuit'), ('standard', 'Standard'), ('premium', 'Premium')], default='gratuit', max_length=20)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('resilie', 'Résilié')], default='actif', max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
            },
        ),
    ]
